<%@ Page Language="C#" AutoEventWireup="true" CodeFile="PatientInfo.aspx.cs" Inherits="EMRSystemMMT.Screens2.PatientInfo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            
        </div>
        <asp:Menu ID="mnuTabs" runat="server" Orientation="Horizontal" BackColor="#999999" BorderStyle="Outset" OnMenuItemClick="mnuTabs_MenuItemClick">
            <Items>
                <asp:MenuItem Text="General" Value="0"></asp:MenuItem>
                <asp:MenuItem Text="History" Value="1"></asp:MenuItem>
                <asp:MenuItem Text="Contacts" Value="2"></asp:MenuItem>
                <asp:MenuItem Selected="True" Text="Finance" Value="3"></asp:MenuItem>
            </Items>
        </asp:Menu>
        <asp:MultiView ID="multiTabs" runat="server" ActiveViewIndex="0">
            <asp:View ID="generalTab" runat="server">
                <asp:Label ID="FirstName" runat="server" Text="First Name"></asp:Label>
                <br />
                <asp:TextBox ID="FirstNameTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="LastName" runat="server" Text="LastName"></asp:Label>
                <br />
                <asp:TextBox ID="LastNameTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="SSN" runat="server" Text="Social Security Number"></asp:Label>
                <br />
                <asp:TextBox ID="SSNTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="DOB" runat="server" Text="Date of Birth"></asp:Label>
                <br />
                <asp:TextBox ID="DOBTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="Address" runat="server" Text="Address"></asp:Label>
                <br />
                <asp:TextBox ID="AddressTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="HomePhone" runat="server" Text="Home Phone"></asp:Label>
                <br />
                <asp:TextBox ID="HomePhoneTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="CellPhone" runat="server" Text="Cell Phone"></asp:Label>
                <br />
                <asp:TextBox ID="CellPhoneTxtBox" runat="server"></asp:TextBox>
                <br />
            </asp:View>
            <asp:View ID="historyTab" runat="server">
                <asp:GridView ID="historyGridView" runat="server" CellPadding="10" GridLines="Vertical" OnSelectedIndexChanged="historyGridView_SelectedIndexChanged" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" HorizontalAlign="Center">
                    <AlternatingRowStyle BackColor="#DCDCDC" />
                    <Columns>
                        <asp:BoundField HeaderText="Date" />
                        <asp:BoundField HeaderText="Type" />
                        <asp:BoundField HeaderText="Notes" />
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                    <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#0000A9" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#000065" />
                </asp:GridView>
                <br />
            </asp:View>
            <asp:View ID="contactsTab" runat="server">
                Contacts<asp:GridView ID="contactsGridView" runat="server" CellPadding="10" GridLines="Vertical" OnSelectedIndexChanged="contactsGridView_SelectedIndexChanged" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" HorizontalAlign="Center">
                    <AlternatingRowStyle BackColor="#DCDCDC" />
                    <Columns>
                        <asp:BoundField HeaderText="Name" />
                        <asp:BoundField HeaderText="Phone Number" />
                        <asp:BoundField HeaderText="Contact Type" />
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                    <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#0000A9" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#000065" />
                </asp:GridView>
                <br />
            </asp:View>
            <asp:View ID="financeTab" runat="server">
                <asp:Label ID="InsuranceCo" runat="server" Text="Insurance Company"></asp:Label>
                <br />
                <asp:TextBox ID="InsuranceCoTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="InsuranceID" runat="server" Text="Insurance ID"></asp:Label>
                <br />
                <asp:TextBox ID="InsuranceIDTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="MedicadeID" runat="server" Text="Medicade ID"></asp:Label>
                <br />
                <asp:TextBox ID="MedicadeIDTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="MedicareID" runat="server" Text="Medicare ID"></asp:Label>
                <br />
                <asp:TextBox ID="MedicareIDTxtBox" runat="server"></asp:TextBox>
                <br />
                <asp:Label ID="Balance" runat="server" Text="Current Balance"></asp:Label>
                <br />
                <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                <br />
            </asp:View>
        </asp:MultiView>
        <asp:Button ID="SaveBtn" runat="server" Text="Save/Update" OnClick="SaveBtn_Click" />
        <br />
        <asp:Button ID="CancelBtn" runat="server" Text="Cancel" OnClick="CancelBtn_Click" />
    </form>
</body>
</html>
